# Generated by Django 5.2.10 on 2026-02-13 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0004_actionhistory_alter_elderpermission_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Предмет')),
                ('grade', models.CharField(max_length=10, verbose_name='Оценка')),
                ('grade_type', models.CharField(choices=[('practice', 'Практика'), ('seminar', 'Семинар'), ('exam', 'Экзамен'), ('other', 'Другое')], max_length=20, verbose_name='Тип')),
                ('date', models.DateField(verbose_name='Дата')),
                ('marked_by', models.CharField(max_length=100, verbose_name='Кто поставил')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='admin_panel.student')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.IntegerField(default=0, verbose_name='Всего пропусков')),
                ('remaining_hours', models.IntegerField(default=20, verbose_name='Осталось часов')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='admin_panel.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='admin_panel.student')),
            ],
            options={
                'verbose_name': 'Профиль студента',
                'verbose_name_plural': 'Профили студентов',
            },
        ),
    ]
