# Generated by Django 5.2.10 on 2026-02-16 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_actionhistory_alter_elderpermission_id'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('teacher', models.CharField(blank=True, max_length=200, verbose_name='Преподаватель')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='admin_panel.group')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('week_type', models.CharField(choices=[('even', 'Чётная'), ('odd', 'Нечётная'), ('both', 'Обе')], max_length=4, verbose_name='Тип недели')),
                ('pair_number', models.IntegerField(verbose_name='Номер пары')),
                ('start_time', models.CharField(default='9:40', max_length=10, verbose_name='Время начала')),
                ('end_time', models.CharField(default='11:10', max_length=10, verbose_name='Время окончания')),
                ('subject', models.CharField(max_length=200, verbose_name='Предмет')),
                ('teacher', models.CharField(blank=True, max_length=200, verbose_name='Преподаватель')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Аудитория')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Лекция'), ('seminar', 'Семинар'), ('practice', 'Практика'), ('lab', 'Лабораторная')], default='lecture', max_length=50, verbose_name='Тип занятия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='admin_panel.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Расписание',
                'ordering': ['day', 'pair_number'],
                'unique_together': {('group', 'day', 'week_type', 'pair_number')},
            },
        ),
    ]
