# Generated by Django 5.2.10 on 2026-02-17 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_actionhistory_alter_elderpermission_id'),
        ('students', '0002_subject_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('display_name', models.CharField(max_length=100, verbose_name='Отображаемое название')),
                ('points', models.FloatField(default=1, verbose_name='Баллы')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тип оценки',
                'verbose_name_plural': 'Типы оценок',
            },
        ),
        migrations.AlterModelOptions(
            name='studentgrade',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='grade',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='is_today',
            field=models.BooleanField(default=False, verbose_name='Сегодняшняя дата'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='points',
            field=models.FloatField(default=1, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='raw_value',
            field=models.CharField(default='', max_length=20, verbose_name='Исходное значение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='students.schedule'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='grade_type',
            field=models.CharField(choices=[('performance', 'Выступление'), ('supplement', 'Дополнение'), ('question', 'Вопрос'), ('plus', '+'), ('minus', '-'), ('numeric_2', '2'), ('numeric_3', '3'), ('numeric_4', '4'), ('numeric_5', '5'), ('custom', 'Другое')], max_length=20, verbose_name='Тип оценки'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_grades', to='admin_panel.student'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.subject'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='custom_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='students.gradetype'),
        ),
        migrations.CreateModel(
            name='ScheduleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('day', models.IntegerField(blank=True, choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], null=True, verbose_name='День недели')),
                ('week_type', models.CharField(blank=True, choices=[('even', 'Чётная'), ('odd', 'Нечётная'), ('both', 'Обе')], max_length=4, null=True)),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('replaces_subject', models.CharField(blank=True, max_length=200, verbose_name='Заменяет предмет')),
                ('new_subject', models.CharField(blank=True, max_length=200, verbose_name='Новый предмет')),
                ('new_teacher', models.CharField(blank=True, max_length=200, verbose_name='Новый преподаватель')),
                ('new_room', models.CharField(blank=True, max_length=100, verbose_name='Новая аудитория')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Занятие отменено')),
                ('is_online', models.BooleanField(default=False, verbose_name='Дистанционно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_comments', to='admin_panel.student')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_comments', to='admin_panel.group')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='students.schedule')),
            ],
            options={
                'verbose_name': 'Комментарий к расписанию',
                'verbose_name_plural': 'Комментарии к расписанию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.FloatField(default=0, verbose_name='Всего баллов')),
                ('target_points', models.IntegerField(default=21, verbose_name='Цель')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='admin_panel.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performance', to='students.subject')),
            ],
            options={
                'verbose_name': 'Успеваемость',
                'verbose_name_plural': 'Успеваемость',
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
