# Generated by Django 5.2.10 on 2026-02-17 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_actionhistory_alter_elderpermission_id'),
        ('students', '0003_gradetype_alter_studentgrade_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('week_type', models.CharField(choices=[('even', 'Чётная'), ('odd', 'Нечётная')], max_length=4, verbose_name='Тип недели')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип недели',
                'verbose_name_plural': 'Типы недель',
                'ordering': ['date'],
            },
        ),
        migrations.RemoveField(
            model_name='schedulecomment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='schedulecomment',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='schedulecomment',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='schedulecomment',
            name='new_room',
        ),
        migrations.RemoveField(
            model_name='schedulecomment',
            name='new_subject',
        ),
        migrations.RemoveField(
            model_name='schedulecomment',
            name='new_teacher',
        ),
        migrations.RemoveField(
            model_name='schedulecomment',
            name='replaces_subject',
        ),
        migrations.RemoveField(
            model_name='schedulecomment',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedulecomment',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='schedulecomment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='schedulecomment',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Срочное'),
        ),
        migrations.AddField(
            model_name='schedulecomment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='students.schedule', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='schedulecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='schedulecomment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_comments', to='admin_panel.student', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='schedulecomment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Конкретная дата'),
        ),
        migrations.AlterField(
            model_name='schedulecomment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_comments', to='admin_panel.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='schedulecomment',
            name='week_type',
            field=models.CharField(blank=True, choices=[('even', 'Чётная'), ('odd', 'Нечётная'), ('both', 'Обе')], max_length=4, null=True, verbose_name='Тип недели'),
        ),
    ]
