# Generated by Django 5.2.10 on 2026-02-19 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_actionhistory_alter_elderpermission_id'),
        ('students', '0004_weektype_remove_schedulecomment_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='custom_type',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='admin_panel.group', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'group')},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата пропуска')),
                ('hours', models.IntegerField(choices=[(1, '1 час'), (2, '2 часа'), (3, '3 часа'), (4, '4 часа'), (5, '5 часов'), (6, '6 часов'), (7, '7 часов'), (8, '8 часов')], verbose_name='Количество часов')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='admin_panel.group', verbose_name='Группа')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to='admin_panel.student', verbose_name='Кто отметил')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='admin_panel.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Пропуск',
                'verbose_name_plural': 'Пропуски',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SeminarSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField(choices=[(1, 'Слот 1'), (2, 'Слот 2')], verbose_name='Номер слота')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_slots', to='admin_panel.group', verbose_name='Группа')),
                ('schedule', models.ForeignKey(limit_choices_to={'lesson_type': 'seminar'}, on_delete=django.db.models.deletion.CASCADE, related_name='seminar_slots', to='students.schedule')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminar_slots', to='admin_panel.student')),
            ],
            options={
                'verbose_name': 'Слот семинара',
                'verbose_name_plural': 'Слоты семинаров',
                'ordering': ['schedule__day', 'schedule__pair_number', 'slot_number'],
                'unique_together': {('schedule', 'slot_number')},
            },
        ),
    ]
