# Generated by Django 5.2.10 on 2026-02-12 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер курса')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Уровень образования',
                'verbose_name_plural': 'Уровни образования',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('delete', '🗑️ Удаление'), ('edit', '✏️ Редактирование'), ('move', '🔄 Перемещение'), ('create', '✅ Создание')], max_length=20, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('object_data', models.JSONField(default=dict, verbose_name='Данные объекта')),
                ('parent_data', models.JSONField(default=dict, verbose_name='Данные родителя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_restored', models.BooleanField(default=False, verbose_name='Восстановлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кэш действия',
                'verbose_name_plural': 'Кэш действий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '✅ Создание'), ('update', '✏️ Редактирование'), ('delete', '🗑️ Удаление'), ('move', '🔄 Перемещение'), ('import', '📎 Импорт'), ('export', '📤 Экспорт')], max_length=20, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('details', models.JSONField(default=dict, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('department_type', models.CharField(choices=[('deanery', '🏛️ Деканат'), ('teacher', '👨\u200d🏫 Преподаватель'), ('administration', '📋 Администрация'), ('other', '🔧 Другое')], default='other', max_length=20, verbose_name='Тип')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='admin_panel.department', verbose_name='Родительский отдел')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Логин')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('position', models.CharField(choices=[('teacher', '👨\u200d🏫 Преподаватель'), ('dean', '🏛️ Декан'), ('deputy_dean', '📋 Зам. декана'), ('methodist', '📊 Методист'), ('admin', '🛠️ Администратор'), ('other', '🔧 Другое')], default='other', max_length=50, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='admin_panel.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='admin_panel.course', verbose_name='Курс')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='admin_panel.educationallevel', verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NavigationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name='Тип контента')),
                ('object_id', models.IntegerField(verbose_name='ID объекта')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('path', models.CharField(max_length=500, verbose_name='Путь')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История навигации',
                'verbose_name_plural': 'История навигации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Логин')),
                ('password', models.CharField(default='', max_length=128, verbose_name='Пароль')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user_type', models.CharField(choices=[('student', '🎓 Студент'), ('elder', '⭐ Староста'), ('dean', '🏛️ Деканат'), ('department', '📋 Отдел'), ('teacher', '👨\u200d🏫 Преподаватель'), ('admin', '🛠️ Администратор')], default='student', max_length=20, verbose_name='Тип пользователя')),
                ('is_elder', models.BooleanField(default=False, verbose_name='Староста')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='admin_panel.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ElderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=dict, verbose_name='Права')),
                ('can_manage_elders', models.BooleanField(default=False, verbose_name='Управление старостами')),
                ('max_students', models.IntegerField(default=100, verbose_name='Макс. студентов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='admin_panel.student', verbose_name='Староста')),
            ],
            options={
                'verbose_name': 'Права старосты',
                'verbose_name_plural': 'Права старост',
            },
        ),
        migrations.CreateModel(
            name='StudyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='admin_panel.educationallevel', verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'Форма обучения',
                'verbose_name_plural': 'Формы обучения',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='admin_panel.studyform', verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='course',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='admin_panel.studyform', verbose_name='Форма обучения'),
        ),
    ]
