# Generated by Django 6.0.1 on 2026-02-11 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('delete', 'Удаление'), ('edit', 'Редактирование'), ('move', 'Перемещение'), ('create', 'Создание')], max_length=20, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('object_data', models.JSONField(default=dict, verbose_name='Данные объекта')),
                ('parent_data', models.JSONField(default=dict, verbose_name='Данные родителя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_restored', models.BooleanField(default=False, verbose_name='Восстановлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кэш действия',
                'verbose_name_plural': 'Кэш действий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavigationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name='Тип контента')),
                ('object_id', models.IntegerField(verbose_name='ID объекта')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('path', models.CharField(max_length=500, verbose_name='Путь')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История навигации',
                'verbose_name_plural': 'История навигации',
                'ordering': ['-created_at'],
            },
        ),
    ]
