# Generated by Django 5.2.10 on 2026-02-13 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedItemCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=50, verbose_name='Тип элемента')),
                ('item_id', models.IntegerField(verbose_name='ID элемента')),
                ('item_data', models.JSONField(verbose_name='Данные элемента')),
                ('parent_data', models.JSONField(default=dict, verbose_name='Данные родителя')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Время удаления')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('is_restored', models.BooleanField(default=False, verbose_name='Восстановлено')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто удалил')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
