# Generated by Django 5.2.10 on 2026-02-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_deleteditemcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=dict, verbose_name='Права')),
                ('can_manage_elders', models.BooleanField(default=False, verbose_name='Управление старостами')),
                ('max_students', models.IntegerField(default=100, verbose_name='Макс. студентов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='admin_panel.student', verbose_name='Староста')),
            ],
            options={
                'verbose_name': 'Права старосты',
                'verbose_name_plural': 'Права старост',
            },
        ),
    ]
