# Generated by Django 5.2.10 on 2026-02-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20260213_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('user_name', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('action', models.CharField(choices=[('create', '✅ Создание'), ('update', '✏️ Редактирование'), ('delete', '🗑️ Удаление'), ('move', '🔄 Перемещение')], max_length=20, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.IntegerField(verbose_name='ID объекта')),
                ('object_data', models.JSONField(verbose_name='Данные до/после')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История действий',
                'verbose_name_plural': 'История действий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='elderpermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
