# Generated by Django 5.2.10 on 2026-02-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_actionhistory_alter_elderpermission_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaselog',
            name='user',
        ),
        migrations.AddField(
            model_name='databaselog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID пользователя'),
        ),
        migrations.AddField(
            model_name='databaselog',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='databaselog',
            name='user_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип пользователя'),
        ),
    ]
